### ISSUE TITLE
Demo_obj.m

### ISSUE THREAD

**Issue by cwo75** [JBKacerovsky/objWriter#1]
Where ist the demo_obj.m ?

**Comment by JBKacerovsky** [comment]
Thank you for raising this issue. It seems Demo_obj.m got deleted accidentally during a revision. I restored the file. 
Please note that Demo_obj.m requires dome files from one of my other repos [matlabSnippets](https://github.com/JBKacerovsky/matlabSnippets) to build the test objects

**Comment by JBKacerovsky** [comment]
[matlabSnippets](https://github.com/JBKacerovsky/matlabSnippets)
